import { NextResponse } from 'next/server'

/**
 * Legacy API route for sitemap.xml
 * Redirects to the Next.js 14 App Router sitemap at /sitemap.xml
 * 
 * This route is kept for backward compatibility with old links/bookmarks
 * but the actual sitemap is now generated by app/sitemap.ts
 */
export async function GET() {
  return NextResponse.redirect('https://www.studio37.cc/sitemap.xml', 301)
}
