export const REQUIRED_SITEMAP_URLS = [
  'https://www.studio37.cc',
  'https://www.studio37.cc/services',
  'https://www.studio37.cc/book-a-session',
  'https://www.studio37.cc/contact',
  'https://www.studio37.cc/tools/pricing',
  'https://www.studio37.cc/tools/package-recommender',
  'https://www.studio37.cc/gallery-experience',
  'https://www.studio37.cc/session-prep',
  'https://www.studio37.cc/locations',
  'https://www.studio37.cc/local-photographer-katy-tx',
  'https://www.studio37.cc/humble',
  'https://www.studio37.cc/atascocita',
  'https://www.studio37.cc/kingwood',
  'https://www.studio37.cc/cleveland',
  'https://www.studio37.cc/navasota',
  'https://www.studio37.cc/plantersville',
  'https://www.studio37.cc/porter',
  'https://www.studio37.cc/splendora',
  'https://www.studio37.cc/waller',
] as const

export const INDEXABILITY_CHECK_URLS = [
  'https://www.studio37.cc/tools/pricing',
  'https://www.studio37.cc/tools/package-recommender',
  'https://www.studio37.cc/session-prep',
  'https://www.studio37.cc/session-prep/portrait',
  'https://www.studio37.cc/session-prep/wedding',
  'https://www.studio37.cc/session-prep/event',
  'https://www.studio37.cc/session-prep/commercial',
] as const
