import { NextRequest, NextResponse } from 'next/server'
import { z } from 'zod'
import { getSupabaseAdmin } from '@/lib/supabaseAdmin'
import { createLogger } from '@/lib/logger'
import { getClientIp, rateLimit } from '@/lib/rateLimit'
import { authErrorResponse, requireAdminRole } from '@/lib/admin-auth'
import { generateBlogPost, generateEmailContent, generateJSON } from '@/lib/ai-client'

const log = createLogger('api/admin/ai-assistant')

const RequestSchema = z.object({
  taskType: z.enum(['blog-post', 'lead-outreach', 'page-blueprint']),
  prompt: z.string().min(8).max(4000),
  saveDraft: z.boolean().optional().default(false),
  options: z.record(z.any()).optional(),
})

function slugify(value: string) {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '')
}

async function createUniqueBlogSlug(title: string) {
  const supabase = getSupabaseAdmin()
  const base = slugify(title) || `blog-${Date.now()}`
  let slug = base
  let n = 1

  while (true) {
    const { data } = await supabase.from('blog_posts').select('id').eq('slug', slug).maybeSingle()
    if (!data) return slug
    n += 1
    slug = `${base}-${n}`
  }
}

export async function POST(request: NextRequest) {
  try {
    await requireAdminRole('editor')

    const ip = getClientIp(request.headers)
    const rl = rateLimit(`admin-ai-assistant:${ip}`, { limit: 30, windowMs: 60 * 1000 })
    if (!rl.allowed) {
      return NextResponse.json({ success: false, error: 'Rate limit exceeded' }, { status: 429 })
    }

    const json = await request.json().catch(() => ({}))
    const parsed = RequestSchema.safeParse(json)
    if (!parsed.success) {
      return NextResponse.json({ success: false, error: 'Invalid request', details: parsed.error.flatten() }, { status: 400 })
    }

    const { taskType, prompt, saveDraft, options } = parsed.data
    const supabase = getSupabaseAdmin()

    if (taskType === 'blog-post') {
      const keywords = Array.isArray(options?.keywords)
        ? options.keywords
        : typeof options?.keywords === 'string'
        ? options.keywords.split(',').map((v: string) => v.trim()).filter(Boolean)
        : ['photography', 'studio37']

      const wordCount = Number(options?.wordCount || 900)
      const tone = (options?.tone as string) || 'professional and friendly'

      const post = await generateBlogPost(prompt, keywords, wordCount, tone)

      let savedPost: any = null
      if (saveDraft) {
        const slug = await createUniqueBlogSlug(post.title)
        const { data, error } = await supabase
          .from('blog_posts')
          .insert({
            title: post.title,
            slug,
            excerpt: post.excerpt,
            content: post.content,
            category: post.category || 'photography',
            tags: post.tags || [],
            meta_description: post.metaDescription,
            meta_keywords: keywords,
            published: false,
          })
          .select('*')
          .single()

        if (!error) savedPost = data
      }

      return NextResponse.json({
        success: true,
        taskType,
        output: {
          ...post,
          suggestedKeywords: keywords,
        },
        saved: !!savedPost,
        savedResource: savedPost,
      })
    }

    if (taskType === 'lead-outreach') {
      const blocks = await generateEmailContent(prompt, {
        templateName: (options?.templateName as string) || 'AI Outreach Draft',
        category: 'outreach',
      })

      let savedTemplate: any = null
      if (saveDraft) {
        const templateName = (options?.templateName as string) || 'AI Outreach Draft'
        const baseSlug = slugify(templateName) || 'ai-outreach-draft'

        let slug = baseSlug
        let i = 1
        while (true) {
          const { data } = await supabase.from('email_templates').select('id').eq('slug', slug).maybeSingle()
          if (!data) break
          i += 1
          slug = `${baseSlug}-${i}`
        }

        const { data, error } = await supabase
          .from('email_templates')
          .insert({
            name: templateName,
            slug,
            subject: (options?.subject as string) || 'A quick note from Studio37',
            category: 'outreach',
            html_content: '<p>Generated by AI Admin Assistant. Open in Visual Builder to render/update HTML.</p>',
            text_content: '',
            blocks_json: blocks,
            is_active: true,
            variables: ['firstName', 'email', 'serviceInterest'],
          })
          .select('*')
          .single()

        if (!error) savedTemplate = data
      }

      return NextResponse.json({
        success: true,
        taskType,
        output: {
          blocks,
          suggestedSubject: (options?.subject as string) || 'A quick note from Studio37',
          note: 'Open the saved draft in Email Templates Visual Builder to review and send.',
        },
        saved: !!savedTemplate,
        savedResource: savedTemplate,
      })
    }

    // page-blueprint
    const blueprintPrompt = `Create a detailed web page blueprint for a photography business admin builder.

User request:
${prompt}

Return strict JSON:
{
  "title": "page title",
  "goal": "primary business conversion goal",
  "sections": [
    {
      "type": "hero|services|gallery|testimonials|cta|faq|contact|custom",
      "title": "section title",
      "purpose": "why this section exists",
      "keyContent": ["bullet", "bullet"],
      "cta": "optional CTA text"
    }
  ],
  "seo": {
    "metaTitle": "",
    "metaDescription": "",
    "targetKeywords": ["", ""]
  },
  "builderHints": ["practical implementation hint"]
}`

    const blueprint = await generateJSON<any>(blueprintPrompt)

    return NextResponse.json({
      success: true,
      taskType,
      output: blueprint,
      saved: false,
    })
  } catch (error: any) {
    if (error?.message === 'UNAUTHORIZED' || error?.message === 'FORBIDDEN') {
      return authErrorResponse(error)
    }
    log.error('AI Admin Assistant failed', undefined, error)
    return NextResponse.json({ success: false, error: error?.message || 'Assistant failed' }, { status: 500 })
  }
}
